/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.73
 * Generated at: 2023-03-27 15:06:05 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class index_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html>\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>RSMM</title>\n");
      out.write("<link rel=\"stylesheet\"\n");
      out.write("	href=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css\"\n");
      out.write("	integrity=\"sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N\"\n");
      out.write("	crossorigin=\"anonymous\">\n");
      out.write("<script src=\"https://kit.fontawesome.com/d2465d9ce4.js\"\n");
      out.write("	crossorigin=\"anonymous\"></script>\n");
      out.write("</head>\n");
      out.write("<body class=\"text-monospace\">\n");
      out.write("	<nav class=\"navbar navbar-expand-lg navbar-light bg-light\">\n");
      out.write("		<a class=\"navbar-brand\" href=\"index.jsp\"><i\n");
      out.write("			class=\"fa-solid fa-server\"></i> Remote Server Monitor &\n");
      out.write("			Management</a>\n");
      out.write("	</nav>\n");
      out.write("	<section class=\"vh-100\">\n");
      out.write("		<div class=\"container h-100\">\n");
      out.write("			<div\n");
      out.write("				class=\"row h-100 d-flex justify-content-center align-items-center\">\n");
      out.write("				<div class=\"col col-xl-10\">\n");
      out.write("					<div class=\"card\" style=\"border-radius: 1rem\">\n");
      out.write("						<div class=\"row g-0\">\n");
      out.write("							<div\n");
      out.write("								class=\"col-md-6 col-lg-5 d-flex align-items-center justify-content-center\">\n");
      out.write("								<img\n");
      out.write("									src=\"https://img.freepik.com/free-vector/mobile-login-concept-illustration_114360-83.jpg?w=826&t=st=1679038466~exp=1679039066~hmac=e9bf28677f56d65d860a2e45253a9f1c76a79f243850e1e2eada3622fc2dc64f\"\n");
      out.write("									alt=\"login form\" class=\"img-fluid\"\n");
      out.write("									style=\"border-radius: 1rem 0 0 1rem\">\n");
      out.write("							</div>\n");
      out.write("							<div class=\"col-md-6 col-lg-7 d-flex align-items-center\">\n");
      out.write("								<div class=\"card-body p-4 p-lg-5 text-black\">\n");
      out.write("									<form action=\"Login\" method=\"post\">\n");
      out.write("										<div class=\"d-flex align-items-center\">\n");
      out.write("											<span class=\"h1 fw-bold\"><i class=\"fa-solid fa-server\"></i>\n");
      out.write("												RSMM</span>\n");
      out.write("										</div>\n");
      out.write("										<h5 class=\"fw-normal mb-1 pb-4\" style=\"letter-spacing: 1px\">Login\n");
      out.write("											to your server</h5>\n");
      out.write("										<div class=\"form-outline mb-1\">\n");
      out.write("											<input type=\"text\" id=\"form2Example17\"\n");
      out.write("												class=\"form-control form-control-lg\" placeholder=\"127.0.0.1\"\n");
      out.write("												name=\"hostname\" required><label class=\"form-label\"\n");
      out.write("												for=\"form2Example17\">Hostname / IP</label>\n");
      out.write("										</div>\n");
      out.write("										<div class=\"form-outline mb-1\">\n");
      out.write("											<input type=\"text\" id=\"form2Example17\"\n");
      out.write("												class=\"form-control form-control-lg\" value=\"22\" name=\"port\"\n");
      out.write("												required><label class=\"form-label\"\n");
      out.write("												for=\"form2Example17\">Port Number</label>\n");
      out.write("										</div>\n");
      out.write("										<div class=\"form-outline mb-1\">\n");
      out.write("											<input type=\"text\" id=\"form2Example17\"\n");
      out.write("												class=\"form-control form-control-lg\" name=\"uname\" required><label\n");
      out.write("												class=\"form-label\" for=\"form2Example17\">Username</label>\n");
      out.write("										</div>\n");
      out.write("										<div class=\"form-outline mb-1\">\n");
      out.write("											<input type=\"password\" id=\"form2Example27\"\n");
      out.write("												class=\"form-control form-control-lg\" name=\"pass\" required><label\n");
      out.write("												class=\"form-label\" for=\"form2Example27\">Password</label>\n");
      out.write("										</div>\n");
      out.write("										");

										String message = request.getParameter("cred");
										if ("invalid".equals(message)) {
											out.println("<div class='alert alert-danger mt-3'>Invalid username or password, please try again!</div>");
										}
										
      out.write("\n");
      out.write("										<div class=\"pt-4 mb-4\">\n");
      out.write("											<input class=\"btn btn-primary btn-lg btn-block\" type=\"submit\"\n");
      out.write("												value=\"Login\">\n");
      out.write("										</div>\n");
      out.write("									</form>\n");
      out.write("								</div>\n");
      out.write("							</div>\n");
      out.write("						</div>\n");
      out.write("					</div>\n");
      out.write("				</div>\n");
      out.write("			</div>\n");
      out.write("		</div>\n");
      out.write("	</section>\n");
      out.write("	<script\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js\"\n");
      out.write("		integrity=\"sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj\"\n");
      out.write("		crossorigin=\"anonymous\"></script>\n");
      out.write("	<script\n");
      out.write("		src=\"https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js\"\n");
      out.write("		integrity=\"sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct\"\n");
      out.write("		crossorigin=\"anonymous\"></script>\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
